version: '3.8'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - 8081:5000
    env_file:
      - .env
    # depends_on:
    #   db:
    #     condition: service_healthy    
    networks:
      - webnet

networks:
  webnet:
