version: '3.8'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - 8090:5000
    env_file:
      - .env
    # depends_on:
    #   db:
    #     condition: service_healthy    
    networks:
      - webnet

#   db:
#     image: postgres:latest
#     restart: always
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - .env
#     ports:
#       - "6565:5432"
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 30s
#       timeout: 30s
#       retries: 3
#     networks:
#       - webnet

# volumes:
#   postgres_data:

networks:
  webnet:
